### ISSUE TITLE
SIP username  / auth setup

### ISSUE THREAD

**Issue by deepdad** [jitsi/jigasi#233]
moved to https://community.jitsi.org/t/account-creation-modification-not-supported/21991

**Comment by deepdad** [comment]
log entries for prosody, jvb and jicofo (I run it on OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1) so the reflection exception can probably be ignored I think it relates to logging only):
```
prosody.log:
Feb 17 10:59:24 jitsi-videobridge.my-domain.com:component	warn	Component not connected, bouncing error for: <iq id='rfJ44-58' type='get' to='jitsi-videobridge.my-domain.com' from='focus@auth.my-domain.com/focus41950763403501'>
Feb 17 10:59:27 jcp561f51c33ee0	info	Incoming Jabber component connection
Feb 17 10:59:27 jitsi-videobridge.my-domain.com:component	info	External component successfully authenticated
Feb 17 10:59:54 callcontrol.my-domain.com:component	warn	Component not connected, bouncing error for: <iq id='rfJ44-78' type='get' to='callcontrol.my-domain.com' from='focus@auth.my-domain.com/focus41950763403501'>

jvb.log:
JVB 2020-02-17 11:34:07.285 FINE: [180] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId 7PZ7q-834):$
JVB 2020-02-17 11:34:11.664 WARNING: [15] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with 565d1dc020e777e not ready yet.
JVB 2020-02-17 11:34:11.664 WARNING: [15] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2020-02-17 11:34:11.665 WARNING: [15] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with ab33cf450c4f5240 not ready yet.
JVB 2020-02-17 11:34:11.665 WARNING: [15] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message
JVB 2020-02-17 11:34:14.395 FINE: [204] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId rfJ44-1864)$

jicofo.log:
root@comp1:/var/log# tail -200 jitsi/jicofo.log
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture.get(LRUHybridCache.java:141)
	at org.glassfish.hk2.utilities.cache.LRUHybridCache.compute(LRUHybridCache.java:280)
	... 97 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/Unmarshaller
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperUtilities$3.run(ClassReflectionHelperUtilities.java:85)
	at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperUtilities$3.run(ClassReflectionHelperUtilities.java:81)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperUtilities.secureGetDeclaredMethods(ClassReflectionHelperUtilities.java:81)
	at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperUtilities.getDeclaredMethodWrappers(ClassReflectionHelperUtilities.java:110)
	at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperUtilities.getAllMethodWrappers(ClassReflectionHelperUtilities.java:169)
	at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperUtilities.getAllMethodWrappers(ClassReflectionHelperUtilities.java:170)
	at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperImpl$3.compute(ClassReflectionHelperImpl.java:61)
	at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperImpl$3.compute(ClassReflectionHelperImpl.java:57)
	at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture$1.call(LRUHybridCache.java:92)
	at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture$1.call(LRUHybridCache.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture.run(LRUHybridCache.java:150)
	at org.glassfish.hk2.utilities.cache.LRUHybridCache.compute(LRUHybridCache.java:269)
	... 97 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.Unmarshaller
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 114 more
MultiException stack 4 of 4
java.lang.IllegalArgumentException: Errors were discovered while reifying SystemDescriptor(
	implementation=org.glassfish.jersey.jaxb.internal.JaxbStringReaderProvider$RootElementProvider
	contracts={javax.ws.rs.ext.ParamConverterProvider}
	scope=javax.inject.Singleton
	qualifiers={}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=null
	proxiable=null
	proxyFormeeScope=null
	analysisName=null
	id=152
	locatorId=0
	identityHashCode=1110225722
	reified=false)
	at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:681)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:441)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2287)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:105)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$10.compute(ServiceLocatorImpl.java:1372)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$10.compute(ServiceLocatorImpl.java:1367)
	at org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:105)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1429)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1355)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1343)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:134)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30)
	at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:307)
	at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:151)
	at org.glassfish.jersey.server.internal.inject.ParamExtractorConfigurator.lambda$init$0(ParamExtractorConfigurator.java:49)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.server.internal.inject.MultivaluedParameterExtractorFactory.get(MultivaluedParameterExtractorFactory.java:68)
	at org.glassfish.jersey.server.internal.inject.AbstractValueParamProvider.get(AbstractValueParamProvider.java:67)
	at org.glassfish.jersey.server.internal.inject.QueryParamValueParamProvider.createValueProvider(QueryParamValueParamProvider.java:57)
	at org.glassfish.jersey.server.internal.inject.AbstractValueParamProvider.getValueProvider(AbstractValueParamProvider.java:93)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParamValueProvider(ParameterValueHelper.java:148)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.createValueProviders(ParameterValueHelper.java:110)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.checkValueProviders(ResourceMethodValidator.java:171)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.checkMethod(ResourceMethodValidator.java:80)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.visitJaxrsResourceMethod(ResourceMethodValidator.java:76)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.visitResourceMethod(ResourceMethodValidator.java:66)
	at org.glassfish.jersey.server.model.ResourceMethod.accept(ResourceMethod.java:875)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:126)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:132)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:132)
	at org.glassfish.jersey.server.model.ComponentModelValidator.access$000(ComponentModelValidator.java:55)
	at org.glassfish.jersey.server.model.ComponentModelValidator$1.run(ComponentModelValidator.java:116)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validate(ComponentModelValidator.java:111)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:366)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:346)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:671)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:428)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:415)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.jitsi.rest.AbstractJettyBundleActivator.doStart(AbstractJettyBundleActivator.java:215)
	at org.jitsi.rest.AbstractJettyBundleActivator.start(AbstractJettyBundleActivator.java:607)
	at org.jitsi.jicofo.auth.AuthBundleActivator.start(AuthBundleActivator.java:233)
	at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)
	at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
	at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
	at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)


Jicofo 2020-02-17 10:59:00.397 INFO: [12] org.eclipse.jetty.server.handler.ContextHandler.doStart() Started o.e.j.s.ServletContextHandler@68056cae{/,null,AVAILABLE}
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.ice4j.socket.jdk8.DelegatingServerSocketChannel (file:/usr/share/jicofo/lib/ice4j-3.0-1-ge854e4e.jar) to method sun.nio.ch.SelChImpl.translateInterestOps(int)
WARNING: Please consider reporting this to the maintainers of org.ice4j.socket.jdk8.DelegatingServerSocketChannel
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jicofo 2020-02-17 10:59:00.438 INFO: [12] org.eclipse.jetty.server.AbstractConnector.doStart() Started MuxServerConnector@47026971{HTTP/1.1,[http/1.1]}{0.0.0.0:8888}
Jicofo 2020-02-17 10:59:00.438 INFO: [12] org.eclipse.jetty.server.Server.doStart() Started @3220ms
Jicofo 2020-02-17 10:59:00.440 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() net.java.sip.communicator.impl.protocol.jabber.extensions.caps.EntityCapsManager.CAPS.http://prosody.im#wBlvgkM1+mhpz81eJoge4hYoI0Q==<query xmlns='http://jabber.org/protocol/disco#info' node='http://prosody.im#wBlvgkM1+mhpz81eJoge4hYoI0Q='><identity category='server' name='Prosody' type='im'/><identity category='pubsub' name='Prosody' type='pep'/><feature var='urn:xmpp:carbons:2'/><feature var='jabber:iq:register'/><feature var='vcard-temp'/><feature var='http://jabber.org/protocol/commands'/><feature var='jabber:iq:roster'/><feature var='urn:xmpp:time'/><feature var='jabber:iq:time'/><feature var='jabber:iq:private'/><feature var='urn:xmpp:ping'/><feature var='jabber:iq:version'/><feature var='urn:xmpp:blocking'/><feature var='msgoffline'/><feature var='http://jabber.org/protocol/disco#info'/><feature var='http://jabber.org/protocol/disco#items'/><feature var='jabber:iq:last'/><feature var='http://jabber.org/protocol/pubsub#publish'/></query>
Jicofo 2020-02-17 10:59:00.441 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.jicofo.auth.URL=XMPP:jitsi-meet.my-domain.com
Jicofo 2020-02-17 10:59:00.457 INFO: [1] org.jitsi.xmpp.component.ComponentBase.log() Component org.jitsi.jicofo. config: 
Jicofo 2020-02-17 10:59:00.457 INFO: [1] org.jitsi.xmpp.component.ComponentBase.log()   ping interval: 10000 ms
Jicofo 2020-02-17 10:59:00.457 INFO: [1] org.jitsi.xmpp.component.ComponentBase.log()   ping timeout: 5000 ms
Jicofo 2020-02-17 10:59:00.457 INFO: [1] org.jitsi.xmpp.component.ComponentBase.log()   ping threshold: 3
Jicofo 2020-02-17 10:59:16.086 WARNING: [21] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[focus@auth.my-domain.com/focus41950763403501] (0) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: system-shutdown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><system-shutdown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>Received SIGTERM</text></stream:error>
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1064)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.base/java.lang.Thread.run(Thread.java:834)
Jicofo 2020-02-17 10:59:16.093 SEVERE: [21] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.connectionClosedOnError().641 XMPP connection closed on error: system-shutdown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><system-shutdown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>Received SIGTERM</text></stream:error>
Jicofo 2020-02-17 10:59:16.093 INFO: [21] org.jitsi.jicofo.ComponentsDiscovery.log() Connection lost - component offline: conference.my-domain.com
Jicofo 2020-02-17 10:59:16.093 WARNING: [21] org.jitsi.jicofo.JitsiMeetServices.log() MUC component went offline: conference.my-domain.com
Jicofo 2020-02-17 10:59:16.093 INFO: [21] org.jitsi.jicofo.ComponentsDiscovery.log() Connection lost - component offline: auth.my-domain.com
Jicofo 2020-02-17 10:59:16.093 INFO: [21] org.jitsi.jicofo.ComponentsDiscovery.log() Connection lost - component offline: jitsi-videobridge.my-domain.com
Jicofo 2020-02-17 10:59:16.094 INFO: [21] org.jitsi.jicofo.BridgeSelector.log() Removing JVB: jitsi-videobridge.my-domain.com
Jicofo 2020-02-17 10:59:16.098 INFO: [21] org.jitsi.jicofo.FocusManager.log() XMPP provider reg state: RegistrationState=Unregistered
Jicofo 2020-02-17 10:59:16.120 WARNING: [49] org.jitsi.jicofo.JvbDoctor.log() Trying to remove a bridge that does not exist anymore: jitsi-videobridge.my-domain.com
Jicofo 2020-02-17 10:59:17.099 INFO: [48] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().684 XMPP reconnecting in: 7
Jicofo 2020-02-17 10:59:18.100 INFO: [48] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().684 XMPP reconnecting in: 6
Jicofo 2020-02-17 10:59:19.101 INFO: [48] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().684 XMPP reconnecting in: 5
Jicofo 2020-02-17 10:59:20.101 INFO: [48] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().684 XMPP reconnecting in: 4
Jicofo 2020-02-17 10:59:20.603 SEVERE: [42] org.jivesoftware.whack.ExternalComponentManager.error() 
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:254)
	at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:257)
	at org.dom4j.io.XMLWriter.flush(XMLWriter.java:272)
	at org.jivesoftware.whack.ExternalComponent.send(ExternalComponent.java:371)
	at org.jivesoftware.whack.ExternalComponentManager.sendPacket(ExternalComponentManager.java:269)
	at org.xmpp.component.AbstractComponent.send(AbstractComponent.java:925)
	at org.jitsi.xmpp.component.ComponentBase.access$400(ComponentBase.java:36)
	at org.jitsi.xmpp.component.ComponentBase$PingTask.run(ComponentBase.java:577)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Jicofo 2020-02-17 10:59:21.101 INFO: [48] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().684 XMPP reconnecting in: 3
Jicofo 2020-02-17 10:59:22.103 INFO: [48] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().684 XMPP reconnecting in: 2
Jicofo 2020-02-17 10:59:23.104 INFO: [48] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().684 XMPP reconnecting in: 1
Jicofo 2020-02-17 10:59:24.105 INFO: [48] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().684 XMPP reconnecting in: 0
Jicofo 2020-02-17 10:59:24.105 INFO: [48] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().684 XMPP reconnecting in: 0
Jicofo 2020-02-17 10:59:24.317 INFO: [48] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: auth.my-domain.com, IQ Stanza (query jabber:iq:version) [to=focus@auth.my-domain.com/focus41950763403501,from=auth.my-domain.com,id=rfJ44-46,type=result,]
Jicofo 2020-02-17 10:59:24.317 INFO: [48] org.jitsi.jicofo.JitsiMeetServices.log() Detected XMPP server version: IQ Stanza (query jabber:iq:version) [to=focus@auth.my-domain.com/focus41950763403501,from=auth.my-domain.com,id=rfJ44-46,type=result,]
Jicofo 2020-02-17 10:59:24.322 INFO: [48] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: conference.my-domain.com, null
Jicofo 2020-02-17 10:59:24.322 INFO: [48] org.jitsi.jicofo.JitsiMeetServices.log() MUC component discovered: conference.my-domain.com
Jicofo 2020-02-17 10:59:24.334 INFO: [48] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: guest.my-domain.com, IQ Stanza (query jabber:iq:version) [to=focus@auth.my-domain.com/focus41950763403501,from=guest.my-domain.com,id=rfJ44-55,type=result,]
Jicofo 2020-02-17 10:59:24.350 INFO: [48] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: focus.my-domain.com, null
Jicofo 2020-02-17 10:59:24.350 INFO: [48] org.jitsi.jicofo.ComponentsDiscovery.log() Services re-discovery interval: 30000
Jicofo 2020-02-17 10:59:24.359 INFO: [48] org.jitsi.jicofo.FocusManager.log() XMPP provider reg state: RegistrationState=Registered
Jicofo 2020-02-17 10:59:25.607 SEVERE: [51] org.jitsi.xmpp.component.ComponentBase.log() Ping timeout for ID: rfJ44-37
Jicofo 2020-02-17 10:59:54.393 SEVERE: [56] org.jitsi.jicofo.discovery.DiscoveryUtil.discoverVersion().200 Failed to discover version, req: <iq to='jitsi-videobridge.my-domain.com' id='rfJ44-84' type='get'><query xmlns='jabber:iq:version'></query></iq>, response: <iq to='focus@auth.my-domain.com/focus41950763403501' from='jitsi-videobridge.my-domain.com' id='rfJ44-84' type='error'><error type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
Jicofo 2020-02-17 10:59:54.393 INFO: [56] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: jitsi-videobridge.my-domain.com, null
Jicofo 2020-02-17 10:59:54.393 INFO: [56] org.jitsi.jicofo.BridgeSelector.log() Added videobridge: jitsi-videobridge.my-domain.com v: null
Jicofo 2020-02-17 10:59:54.393 WARNING: [56] org.jitsi.jicofo.BridgeSelector.log() No pub-sub node mapped for jitsi-videobridge.my-domain.com
Jicofo 2020-02-17 10:59:54.395 INFO: [49] org.jitsi.jicofo.JvbDoctor.log() Scheduled health-check task for: jitsi-videobridge.my-domain.com
```
