### ISSUE TITLE
Failed to process an incoming session initiate

### ISSUE THREAD

**Issue by Kidav** [jitsi/jigasi#26]
Sip calls stopped work after upgraiding to last versions of jicofo, jigasi, videobrdge. Next errors appears in jigasi.log
```javascript
impl.protocol.jabber.CallPeerJabberImpl.processSessionInitiate().821 Failed to process an incoming session initiate
java.lang.NullPointerException
        at net.java.sip.communicator.impl.protocol.jabber.CallPeerMediaHandlerJabberImpl.processOffer(CallPeerMediaHandlerJabberImpl.java:1753)
        at net.java.sip.communicator.impl.protocol.jabber.CallPeerJabberImpl.processSessionInitiate(CallPeerJabberImpl.java:798)
        at net.java.sip.communicator.impl.protocol.jabber.CallJabberImpl.processSessionInitiate(CallJabberImpl.java:1001)
        at net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl$2.run(OperationSetBasicTelephonyJabberImpl.java:1024)
```
After some debugging was detected in 
https://github.com/jitsi/jitsi/blob/master/src/net/java/sip/communicator/impl/protocol/jabber/CallPeerMediaHandlerJabberImpl.java#L1668
 that offer contain 6 nodes of content

```xml
<content  creator='initiator' name='audio' senders='both'><description xmlns='urn:xmpp:jingle:apps:rtp:1' media='audio' maxptime='60'><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='111' name='opus' clockrate='48000' channels='2'><parameter xmlns='urn:xmpp:jingle:apps:rtp:1' name='minptime' value='10'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:1' name='useinbandfec' value='1'/></payload-type><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='103' name='ISAC' clockrate='16000'/><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='104' name='ISAC' clockrate='32000'/><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='0' name='PCMU' clockrate='8000'/><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='8' name='PCMA' clockrate='8000'/><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='106' name='CN' clockrate='32000'/><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='105' name='CN' clockrate='16000'/><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='13' name='CN' clockrate='8000'/><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='126' name='telephone-event' clockrate='8000'/><rtp-hdrext xmlns='urn:xmpp:jingle:apps:rtp:rtp-hdrext:0' id='1' uri='urn:ietf:params:rtp-hdrext:ssrc-audio-level'/><source xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' ssrc='834591721'><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='cname' value='mixed'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='label' value='mixedlabelaudio0'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='msid' value='mixedmslabel mixedlabelaudio0'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='mslabel' value='mixedmslabel'/><ssrc-info xmlns='http://jitsi.org/jitmeet' owner='jvb'/></source><source xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' ssrc='1601724477'><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='cname' value='0sDETmsbNQQEJmB'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='msid' value='96aae3c4-b1a7-4d5c-b395-f9bd9a35d6c9 6d1a2178-6736-4eb2-8913-26601225bae7'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='mslabel' value='96aae3c4-b1a7-4d5c-b395-f9bd9a35d6c9'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='label' value='6d1a2178-6736-4eb2-8913-26601225bae7'/><ssrc-info xmlns='http://jitsi.org/jitmeet' owner='4617604@gr.conference.com/w_ukk92u'/></source><source xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' ssrc='2487888203'><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='cname' value='jSMmt5bSVwFk9J3'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='msid' value='9ccbf665-afcd-491a-adb0-cc6c1b53ec08 689ab060-eeb7-4e05-a1a0-a8a7feccf6e5'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='mslabel' value='9ccbf665-afcd-491a-adb0-cc6c1b53ec08'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='label' value='689ab060-eeb7-4e05-a1a0-a8a7feccf6e5'/><ssrc-info xmlns='http://jitsi.org/jitmeet' owner='4617604@gr.conference.com/w_s6kpov'/></source></description><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' pwd='7eg7n7ps6urp67udqb8kdmv25t' ufrag='8dh7m1aae3cmvq'><rtcp-mux xmlns='urn:xmpp:jingle:transports:ice-udp:1'/><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' hash='sha-1' required='false'>0D:C5:38:4E:7E:1D:B0:67:EA:62:EB:75:87:B1:D7:73:3B:EC:48:38</fingerprint><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='1' generation='0' id='78b795013ec6d70d46bd2060ee51c3b063a06d20' network='0' priority='2130706431' protocol='ssltcp' tcptype='passive' type='host' ip='10.240.104.214' port='4443'/><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='3' generation='0' id='78b795013ec6d70d46bd2060ee51c3b0395c82f9' network='0' priority='2130706431' protocol='udp' type='host' ip='10.240.104.214' port='10000'/><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='2' generation='0' id='78b795013ec6d70d46bd2060ee51c3b0689ac6da' network='0' priority='1694498815' protocol='ssltcp' tcptype='passive' type='srflx' ip='1.1.1.1' port='4443' rel-addr='10.240.104.214' rel-port='4443'/><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='4' generation='0' id='78b795013ec6d70d46bd2060ee51c3b07cbc80d8' network='0' priority='1677724415' protocol='udp' type='srflx' ip='1.1.1.1' port='10000' rel-addr='10.240.104.214' rel-port='10000'/></transport><bundle xmlns='http://estos.de/ns/bundle'/></content>
<content  creator='initiator' name='video' senders='both'><description xmlns='urn:xmpp:jingle:apps:rtp:1' media='video'><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='100' name='VP8' clockrate='90000'><rtcp-fb xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0' type='ccm' subtype='fir'/><rtcp-fb xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0' type='nack'/><rtcp-fb xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0' type='nack' subtype='pli'/><rtcp-fb xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0' type='goog-remb'/></payload-type><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='116' name='red' clockrate='90000'/><payload-type xmlns='urn:xmpp:jingle:apps:rtp:1' id='117' name='ulpfec' clockrate='90000'/><rtp-hdrext xmlns='urn:xmpp:jingle:apps:rtp:rtp-hdrext:0' id='2' uri='urn:ietf:params:rtp-hdrext:toffset'/><rtp-hdrext xmlns='urn:xmpp:jingle:apps:rtp:rtp-hdrext:0' id='3' uri='http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time'/><source xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' ssrc='1473252260'><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='cname' value='mixed'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='label' value='mixedlabelvideo0'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='msid' value='mixedmslabel mixedlabelvideo0'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='mslabel' value='mixedmslabel'/><ssrc-info xmlns='http://jitsi.org/jitmeet' owner='jvb'/></source><source xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' ssrc='1580321886' videoPurpose='primary'><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='cname' value='2hDJk2STVEqK9ULZ'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='msid' value='d11690a7-a35e-446c-a797-7fb4a3bf8296 e7acc121-e24c-44a1-a9ec-39945fceb8f8'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='mslabel' value='d11690a7-a35e-446c-a797-7fb4a3bf8296'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='label' value='e7acc121-e24c-44a1-a9ec-39945fceb8f8'/><ssrc-info xmlns='http://jitsi.org/jitmeet' owner='4617604@gr.conference.com/w_ukk92u'/></source><source xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' ssrc='3314974369' videoPurpose='primary'><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='cname' value='2EMN7rV1RDnnnil'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='msid' value='b8c3a50a-49b8-4638-b6f1-1490cb5519eb bc73885a-2e9b-4f6d-9314-14d532c2bd2a'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='mslabel' value='b8c3a50a-49b8-4638-b6f1-1490cb5519eb'/><parameter xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' name='label' value='bc73885a-2e9b-4f6d-9314-14d532c2bd2a'/><ssrc-info xmlns='http://jitsi.org/jitmeet' owner='4617604@gr.conference.com/w_s6kpov'/></source></description><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' pwd='7eg7n7ps6urp67udqb8kdmv25t' ufrag='8dh7m1aae3cmvq'><rtcp-mux xmlns='urn:xmpp:jingle:transports:ice-udp:1'/><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' hash='sha-1' required='false'>0D:C5:38:4E:7E:1D:B0:67:EA:62:EB:75:87:B1:D7:73:3B:EC:48:38</fingerprint><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='1' generation='0' id='78b795013ec6d70d46bd2060ee51c3b063a06d20' network='0' priority='2130706431' protocol='ssltcp' tcptype='passive' type='host' ip='10.240.104.214' port='4443'/><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='3' generation='0' id='78b795013ec6d70d46bd2060ee51c3b0395c82f9' network='0' priority='2130706431' protocol='udp' type='host' ip='10.240.104.214' port='10000'/><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='2' generation='0' id='78b795013ec6d70d46bd2060ee51c3b0689ac6da' network='0' priority='1694498815' protocol='ssltcp' tcptype='passive' type='srflx' ip='1.1.1.1' port='4443' rel-addr='10.240.104.214' rel-port='4443'/><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='4' generation='0' id='78b795013ec6d70d46bd2060ee51c3b07cbc80d8' network='0' priority='1677724415' protocol='udp' type='srflx' ip='1.1.1.1' port='10000' rel-addr='10.240.104.214' rel-port='10000'/></transport><bundle xmlns='http://estos.de/ns/bundle'/></content>
<content  creator='initiator' name='data' senders='both'><description xmlns='urn:xmpp:jingle:apps:rtp:1' media='application'/><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' pwd='7eg7n7ps6urp67udqb8kdmv25t' ufrag='8dh7m1aae3cmvq'><rtcp-mux xmlns='urn:xmpp:jingle:transports:ice-udp:1'/><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' hash='sha-1' required='false'>0D:C5:38:4E:7E:1D:B0:67:EA:62:EB:75:87:B1:D7:73:3B:EC:48:38</fingerprint><sctpmap xmlns='urn:xmpp:jingle:transports:dtls-sctp:1' number='5000' protocol='webrtc-datachannel' streams='1024'/><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='1' generation='0' id='78b795013ec6d70d46bd2060ee51c3b063a06d20' network='0' priority='2130706431' protocol='ssltcp' tcptype='passive' type='host' ip='10.240.104.214' port='4443'/><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='3' generation='0' id='78b795013ec6d70d46bd2060ee51c3b0395c82f9' network='0' priority='2130706431' protocol='udp' type='host' ip='10.240.104.214' port='10000'/><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='2' generation='0' id='78b795013ec6d70d46bd2060ee51c3b0689ac6da' network='0' priority='1694498815' protocol='ssltcp' tcptype='passive' type='srflx' ip='1.1.1.1' port='4443' rel-addr='10.240.104.214' rel-port='4443'/><candidate xmlns='urn:xmpp:jingle:transports:ice-udp:1' component='1' foundation='4' generation='0' id='78b795013ec6d70d46bd2060ee51c3b07cbc80d8' network='0' priority='1677724415' protocol='udp' type='srflx' ip='1.1.1.1' port='10000' rel-addr='10.240.104.214' rel-port='10000'/></transport><bundle xmlns='http://estos.de/ns/bundle'/></content>
<content  name='audio'/>
<content  name='video'/>
<content  name='data'/>
```

3 of them normal and 3 is empty.

**Comment by Kidav** [comment]
Just for test I putted this snipped
```java
for (Iterator<ContentPacketExtension> iterator = offer.iterator(); iterator.hasNext();) {
            ContentPacketExtension offerPart = iterator.next();
            if (offerPart.getFirstChildOfType(IceUdpTransportPacketExtension.class) == null) {
                iterator.remove();
            }
        }
```
to filter empty nodes. And now jigasi connects to the conference but without voice. In jigasi.log apears such errors

```java
org.jitsi.impl.neomedia.transform.SinglePacketTransformer.error() Failed to transform RawPacket(s)!
java.lang.NullPointerException
        at org.jitsi.impl.neomedia.transform.DebugTransformEngine$MyRTPPacketTransformer.transform(DebugTransformEngine.java:175)
        at org.jitsi.impl.neomedia.transform.SinglePacketTransformer.transform(SinglePacketTransformer.java:94)
        at org.jitsi.impl.neomedia.transform.TransformEngineChain$PacketTransformerChain.transform(TransformEngineChain.java:303)
        at org.jitsi.impl.neomedia.transform.TransformUDPOutputStream.createRawPacket(TransformUDPOutputStream.java:76)
        at org.jitsi.impl.neomedia.RTPConnectorOutputStream.write(RTPConnectorOutputStream.java:432)
        at net.sf.fmj.media.rtp.util.RTPPacketSender.sendTo(RTPPacketSender.java:61)
        at net.sf.fmj.media.rtp.util.PacketFilter.sendTo(PacketFilter.java:122)
        at net.sf.fmj.media.rtp.RTPTransmitter.transmit(RTPTransmitter.java:92)
        at net.sf.fmj.media.rtp.RTPTransmitter.TransmitPacket(RTPTransmitter.java:115)
        at net.sf.fmj.media.rtp.RTPSinkStream.transmitAudio(RTPSinkStream.java:148)
        at net.sf.fmj.media.rtp.RTPSinkStream.transferData(RTPSinkStream.java:119)
        at net.sf.fmj.media.multiplexer.RawBufferMux$RawBufferSourceStream.run(RawBufferMux.java:380)
        at java.lang.Thread.run(Thread.java:745)
        at net.sf.fmj.media.util.MediaThread.run(MediaThread.java:202)
```
Are there some changes in protocol-jabber.jar that do jigasi incompatible with current jicofo ?

**Comment by gpolitis** [comment]
I believe this exception is fixed in recent versions of libjitsi, so you could try replacing lib/libjitsi-1.0-SNAPSHOT.jar with the latest from here https://github.com/jitsi/jitsi-maven-repository. The inconvenience then would be that you would also have to update the dependencies of libjitsi. Alternatively, you could try to mavenize Jigasi so that it pulls the correct dependencies from maven. The later is in our roadmap.

**Comment by Kidav** [comment]
Thanx for your ansver.
I checked fresh jigasi 1.0-99 and with last 
https://github.com/jitsi/jitsi-maven-repository/blob/master/snapshots/org/jitsi/libjitsi/1.0-SNAPSHOT/libjitsi-1.0-20160202.214638-87.jar
But same error occurs :(
```log
impl.protocol.jabber.CallPeerJabberImpl.processSessionInitiate().821 Failed to process an incoming session initiate
java.lang.NullPointerException
        at net.java.sip.communicator.impl.protocol.jabber.CallPeerMediaHandlerJabberImpl.processOffer(CallPeerMediaHandlerJabberImpl.java:1753)
...
```

**Comment by Kidav** [comment]
Still same problem. All posible jars of jigasi was replaced with corresponding from current jitsi-maven-repository. As I see issue https://github.com/jitsi/jigasi/issues/27 points out to the same problem

**Comment by Kidav** [comment]
Any news, suggestions? Does this issue in your roadmap?

**Comment by damencho** [comment]
I've created an issue to track update and fixing latest jigasi.
https://github.com/jitsi/jigasi/issues/29
