### ISSUE TITLE
When using JWT based auth with jicofo,  any telephony user joining before the host arrives shown an error saying not-authorised and call is ended.

### ISSUE THREAD

**Issue by LohithBlaze** [jitsi/jigasi#307]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
when using JWT based auth, when a telephony user tries to join a room before the host has arrived, the jigasi gets an error as not-authorised from jicofo and the call gets  ended

## Current behavior
if the host has not arrived, all telephony users calls are being ended

## Expected Behavior
If the host has not arrived, the telephony users calls should be kept active with any message.

## Possible Solution
Dont know

## Steps to reproduce
1. Create a room.
2. You are shown the prompt "waiting for the host to join the room"
3. a telephony user tries to join
4. after some time, the call gets ended.

**Comment by LohithBlaze** [comment]
```
Jigasi 2020-08-12 19:04:52.079 SEVERE: [429] org.jitsi.jigasi.JvbConference.inviteFocus().1456 [ctx=15972392919001642598523] Could not invite the focus to the conference
org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from focus.meet.lohithblaze.ai: XMPPError: not-authorized - auth
	at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:132)
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:263)
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:214)
	at org.jitsi.jigasi.JvbConference.inviteFocus(JvbConference.java:1450)
	at org.jitsi.jigasi.JvbConference.joinConferenceRoom(JvbConference.java:793)
	at org.jitsi.jigasi.JvbConference.registrationStateChanged(JvbConference.java:606)
	at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:187)
	at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:141)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1389)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:970)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:795)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:500)
	at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)
```

**Comment by f-asa** [comment]
@LohithBlaze do you still have this issue ?
