### ISSUE TITLE
failed to start jigasi

### ISSUE THREAD

**Issue by huiwu** [jitsi/jigasi#31]
Hi Jitsi Team,

I failed to start jigasi with the following log:

2016-05-06 16:28:52.805 INFO: [11] impl.netaddr.NetworkConfigurationWatcher.checkNetworkInterfaces().398 Currently Active eth0:[/10.172.110.254]
2016-05-06 16:28:52.807 INFO: [11] impl.dns.DnsUtilActivator.logDNSServers().293 Loading or Reloading resolver config, default DNS servers are: 10.143.22.118, 10.143.22.116,
2016-05-06 16:28:52.807 INFO: [11] impl.dns.DnsUtilActivator.logDNSServers().293 Loading or Reloading resolver config, default DNS servers are: 10.143.22.118, 10.143.22.116,
2016-05-06 16:28:52.962 INFO: [10] impl.packetlogging.PacketLoggingActivator.start().100 Packet Logging Service ...[REGISTERED]
2016-05-06 16:28:52.968 INFO: [10] service.notification.NotificationServiceActivator.start().48 Notification Service...[  STARTED ]
2016-05-06 16:28:52.973 INFO: [10] service.notification.NotificationServiceActivator.start().55 Notification Service ...[REGISTERED]
2016-05-06 16:28:53.356 SEVERE: [10] org.jitsi.impl.neomedia.device.DeviceConfiguration.error() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer with JMF.
java.lang.IllegalStateException: audioSystem
        at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:155)
        at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:135)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1046)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:365)
        at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:159)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:151)
        at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:95)
        at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:172)
        at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:124)
        at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:391)
        at org.jitsi.impl.osgi.framework.BundleImpl.start(Unknown Source)
                                                                                                                                   86,1          55%
                                                                                                                                   86,1          55%
        at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(Unknown Source)
2016-05-06 16:28:53.416 INFO: [10] impl.neomedia.NeomediaActivator.start().542 Audio Notifier Service ...[REGISTERED]
2016-05-06 16:28:53.432 INFO: [10] impl.version.VersionActivator.start() Jitsi Version: Jitsi 2.9.0.build.by.SVN
2016-05-06 16:28:53.434 SEVERE: [22] util.UtilActivator.uncaughtException().119 An uncaught exception occurred in thread=Thread[Thread-11,5,main] and
java.lang.NullPointerException
        at org.jitsi.impl.neomedia.transform.zrtp.ZrtpFortunaEntropyGatherer$GatherAudio.run(ZrtpFortunaEntropyGatherer.java:276)
2016-05-06 16:28:53.448 FINE: [10] plugin.reconnectplugin.ReconnectPluginActivator.start().249 Found 0 already installed providers.
2016-05-06 16:28:53.561 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() net.java.sip.communicator.impl.protocol.sip.acc1403273
2016-05-06 16:28:53.561 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() net.java.sip.communicator.impl.protocol.sip.acc1403273
.polylink.net
2016-05-06 16:28:53.561 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() net.java.sip.communicator.impl.protocol.sip.acc1403273
2016-05-06 16:28:53.562 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() net.java.sip.communicator.impl.protocol.sip.acc1403273
2016-05-06 16:28:53.562 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() net.java.sip.communicator.impl.protocol.sip.acc1403273
@

OS version is ubuntu14.04
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch

Jitsi version is :1.0-99

Would you please give some advice on it.

Thanks with regards,

huiwu

**Comment by damencho** [comment]
Please use the mailinglist for questions, before opening issues. 
These exceptions are normal and harmless.
