### ISSUE TITLE
jigasi can't call-out, no invite call possible, no telephone icon appear

### ISSUE THREAD

**Issue by comsyspro** [jitsi/jigasi#423]
I successfully configured the jigasi call-in with asterisk and sipgate. I also used both - the installed jigasi service - and - also the manual "Install and run" way. Both worked for call-in. But I can't get call-out working and I can't see any telephone icon appearing in the toolbar. When I make an invitation with a telephone number I get an error message and following jicofo log:
![image](https://user-images.githubusercontent.com/13809377/171339851-6b32680b-658c-4cb4-a36a-4d071ca4b37c.png)

`Jicofo 2022-06-01 08:03:41.026 INFO: [42] JigasiIqHandler.handleRequest#74: Accepted jigasi request from appealingseriesdivertfast@conference.domain.com/14ddcf9c: <iq xmlns='jabber:client' to='focus@auth.domain.com/focus' from='appealingseriesdivertfast@conference.domain.com/14ddcf9c' id='*********' type='set'><dial xmlns='urn:xmpp:rayo:1' from='fromnumber' to='0123456789'><header xmlns='urn:xmpp:rayo:1' name='JvbRoomName' value='appealingseriesdivertfast@conference.domain.com'/></dial></iq>`

`Jicofo 2022-06-01 08:03:41.026 WARNING: [74] JigasiIqHandler.inviteJigasi#102: Request failed, no instances available: <iq xmlns='jabber:client' to='focus@auth.domain.com/focus' from='appealingseriesdivertfast@conference.domain.com/14ddcf9c' id='*********' type='set'><dial xmlns='urn:xmpp:rayo:1' from='fromnumber' to='0123456789'><header xmlns='urn:xmpp:rayo:1' name='JvbRoomName' value='appealingseriesdivertfast@conference.domain.com'/></dial></iq>`

Also the "tail -f jigasi.log" file doesn't debug anything when pressing the invite call button. Where is the problem and why there is no telephone icon in the toolbar?

**Comment by damencho** [comment]
Here: https://github.com/jitsi/jigasi/blob/ae4b5a4404d0f019cfdfe0a4f2e95a15ae898e1e/jigasi-home/sip-communicator.properties#L80

yes, base64 as pointed in the template.

**Comment by comsyspro** [comment]
Ok, I came a step further. 

1. Here was already a base64 string set like net.java.sip.communicator.impl.protocol.jabber.acc-xmpp-1.PASSWORD=**abcdefghijkl==**
2. I took that string **abcdefghijkl==** and decoded it with **echo  'abcdefghijkl==' | base64 --decode** so I got the resulting password **xyz**
3. I took this password xyz and created: **prosodyctl register jigasi auth.my.domain.com xyz**
4. then i changed the password in this section:
org.jitsi.jigasi.xmpp.acc.USER_ID=jigasi@auth.my.domain.com
**org.jitsi.jigasi.xmpp.acc.PASS=xyz**
org.jitsi.jigasi.xmpp.acc.ANONYMOUS_AUTH=false

With all that done I get following jigasi.log error message:
```
2022-06-01 17:33:58.118 SEVERE: [69] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin().1003 Failed to connect to XMPP service
org.jivesoftware.smack.SmackException$SecurityRequiredByClientException: SSL/TLS required by client but not supported by server
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:390)
        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1309)
        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:970)
        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:795)
        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:500)
        at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)
2022-06-01 17:33:58.120 SEVERE: [69] org.jitsi.jigasi.JvbConference.registrationStateChanged().670 [ctx=16540976376721335888952] XMPP Connection failed. RegistrationStateChangeEvent[ oldState=Registering; newState=RegistrationState=Connection Failed; userRequest=false; reasonCode=6; reason=SSL/TLS required by client but not supported by server]
2022-06-01 17:34:07.741 SEVERE: [65] org.jitsi.jigasi.xmpp.CallControlMucActivator.processIQInternal().584 [ctx=16540976376721335888952] Error processing RayoIq
java.lang.Exception: Fail to join muc!
        at org.jitsi.jigasi.xmpp.CallControlMucActivator$WaitToJoinRoom.waitToJoinRoom(CallControlMucActivator.java:681)
        at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.setDialResponseAndRegisterHangUpHandler(CallControlMucActivator.java:616)
        at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.processIQInternal(CallControlMucActivator.java:573)
        at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.lambda$processIQ$0(CallControlMucActivator.java:534)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-01 17:34:27.758 WARNING: [48] org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary() XMPPConnection was not authenticated
```

**Comment by damencho** [comment]
> 4\. then i changed the password in this section:
>     org.jitsi.jigasi.xmpp.acc.USER_ID=[jigasi@auth.my.domain.com](mailto:jigasi@auth.my.domain.com)
>     **org.jitsi.jigasi.xmpp.acc.PASS=xyz**
>     org.jitsi.jigasi.xmpp.acc.ANONYMOUS_AUTH=false

Check my comment above with the link, you are editing the wrong config. This is the client connection when jigasi connects to a meeting. The account for connecting to the shard is net.java.sip.communicator.impl.protocol.jabber....

**Comment by comsyspro** [comment]
In my jitsi installation there already was a password string set like et.java.sip.communicator.impl.protocol.jabber.acc-xmpp-1.PASSWORD=abcdefghijkl==
So I took this string and decoded it back to a password string and then I created the jigasi user with this password for auth domain. With that done the first error message  "SASLError using SCRAM-SHA-1: not-authorized" has gone. Where does the password abcdefghijkl== come from? Which passwords must match in which config files?

**Comment by damencho** [comment]
This is how to convert it: https://github.com/jitsi/jigasi/blob/ae4b5a4404d0f019cfdfe0a4f2e95a15ae898e1e/debian/postinst#L144

The props: `org.jitsi.jigasi.xmpp.acc` are used only when the call is being created, whether it is dial-in or dial-out. In order jicofo to be able to ask jigasi to join, jigasi needs to be connected to the shard, for which you need to configure the settings with all the `net.java.sip.communicator.impl.protocol.jabber.acc...` props.

**Comment by comsyspro** [comment]
Ok, thank you very much! Now it also works the other way with **echo -n mypassword | base64 -**. So here was the error that I used this command **echo mypassword | base64** instead. A last question to this setting **org.jitsi.jigasi.xmpp.acc.ALLOW_NON_SECURE=true**: Is this security relevant? Is there an alternative or do I need another certificate with subdomains to uncomment this again? If yes, which subdomain names have to be included in the the certificate (letsencrypt)? Thank you.
