### ISSUE TITLE
Connection works but no sound

### ISSUE THREAD

**Issue by Ulrar** [jitsi/jigasi#43]
Hi,

Just installed jitsi-meet and jigasi, looks like it does come online fine but when I try to call someone from a room (outgoing) it does connect when they pick up, but neither of us can hear anything.

I find two errors in the logs : 
`StateChanged(RegistrationStateChangeEvent) of net.java.sip.communicator.impl.protocol.jabber.OperationSetPersistentPresenceJabberImpl$RegistrationStateListener@532e18d4
java.lang.IllegalArgumentException: Connection cannot be anonymous
	at org.jivesoftware.smackx.packet.VCard.checkAuthenticated(VCard.java:571)
	at org.jivesoftware.smackx.packet.VCard.load(VCard.java:511)
	at net.java.sip.communicator.impl.protocol.jabber.OperationSetPersistentPresenceJabberImpl.createAccountPhotoPresenceInterceptor(OperationSetPersistentPresenceJabberImpl.java:1898)
	at net.java.sip.communicator.impl.protocol.jabber.OperationSetPersistentPresenceJabberImpl$RegistrationStateListener.registrationStateChanged(OperationSetPersistentPresenceJabberImpl.java:1106)
	at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:187)
	at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:141)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1314)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:944)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:755)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:468)
	at org.jitsi.jigasi.RegisterThread.run(RegisterThread.java:58)
`

`2016-12-06 16:16:42.888 SEVERE: [104] net.sf.fmj.media.Log.error() Failed to build a graph for the given custom options.
2016-12-06 16:16:42.889 SEVERE: [104] net.sf.fmj.media.Log.error() Failed to realize: net.sf.fmj.media.ProcessEngine@29928f05
2016-12-06 16:16:42.892 SEVERE: [104] net.sf.fmj.media.Log.error()   Cannot build a flow graph with the customized options:
2016-12-06 16:16:42.892 SEVERE: [104] net.sf.fmj.media.Log.error()     Unable to transcode format: LINEAR, 48000.0 Hz, 16-bit, Mono, LittleEndian, Signed
2016-12-06 16:16:42.892 SEVERE: [104] net.sf.fmj.media.Log.error()       to: opus/rtp, 48000.0 Hz, Stereo
2016-12-06 16:16:42.893 SEVERE: [104] net.sf.fmj.media.Log.error()       outputting to: raw.rtp
2016-12-06 16:16:42.893 SEVERE: [104] net.sf.fmj.media.Log.error()     Unable to add customed codecs: 
2016-12-06 16:16:42.893 SEVERE: [104] net.sf.fmj.media.Log.error()       org.jitsi.impl.neomedia.audiolevel.AudioLevelEffect2@75783419
2016-12-06 16:16:42.894 SEVERE: [103] net.sf.fmj.media.Log.error() Error: Unable to realize net.sf.fmj.media.ProcessEngine@29928f05
`

After that the call is created then connected, no errors during that process, which seems weird. I'd assume the errors would be while connecting, not before.
In any case I tried both version of jigasi (107 and 108) and same thing. If that matters I only tried the deb packages.

Thanks

**Comment by damencho** [comment]
Please use the mailinglist when you have questions and problems, before opening new issues.

I recently tested it on a new deployment and it was working. Can you check your logs of jigasi on startup for errors? I suspect a problem loading the native libraries.

**Comment by rasos** [comment]
Same issue here on Debian stretch:

2018-01-23 23:08:05.081 SEVERE: [185] net.sf.fmj.media.Log.error()   Unable to handle format: LINEAR, 48000.0 Hz, 16-bit, Mono, LittleEndian, Signed
2018-01-23 23:08:05.082 SEVERE: [185] net.sf.fmj.media.Log.error() Failed to prefetch: net.sf.fmj.media.ProcessEngine@7266e4d0
2018-01-23 23:08:05.086 SEVERE: [183] net.sf.fmj.media.Log.error() Error: Unable to prefetch net.sf.fmj.media.ProcessEngine@7266e4d0

It seems a PulseAudio Library is missing - but which one?

2018-01-23 23:07:44.731 SEVERE: [10] org.jitsi.impl.neomedia.device.DeviceConfiguration.log() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer with JMF.
java.lang.IllegalStateException: audioSystem
        at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:155)
        at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:135)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1046)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:365)
        at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:160)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.initializeService(LibJitsiImpl.java:196)
        at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.getService(LibJitsiImpl.java:131)
        at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:91)
        at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:95)
        at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:172)
        at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:124)
        at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:391)
        at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:293)
        at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:460)
        at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:126)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:111)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:17)
        at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:220)
