### ISSUE TITLE
Vosk transcription results in ClassNotFoundException for StaticException

### ISSUE THREAD

**Issue by dj95** [jitsi/jigasi#472]
## Description

When using the transcription feature with vosk, the websocket connection gets established by jigasi, but somehow it throws an exception. We currently use the docker image `jitsi/jigasi:stable-8252`.

---

## Current behavior

```
2023-02-07 15:17:33.509 WARNING: [155] org.eclipse.jetty.util.TypeUtil.mapToService: Service Provider failed to load
java.util.ServiceConfigurationError:
        at org.eclipse.jetty.util.ServiceLoaderSpliterator$ServiceProvider.get(ServiceLoaderSpliterator.java:101)
        at org.eclipse.jetty.util.TypeUtil.mapToService(TypeUtil.java:768)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at org.eclipse.jetty.util.ServiceLoaderSpliterator.tryAdvance(ServiceLoaderSpliterator.java:46)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.eclipse.jetty.websocket.core.WebSocketExtensionRegistry.<init>(WebSocketExtensionRegistry.java:34)
        at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:55)
        at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:49)
        at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:43)
        at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:67)
        at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:76)
        at org.jitsi.jigasi.transcription.VoskTranscriptionService.sendSingleRequest(VoskTranscriptionService.java:143)
        at org.jitsi.jigasi.transcription.Participant.lambda$sendRequest$1(Participant.java:697)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.ServiceConfigurationError: org.eclipse.jetty.websocket.core.Extension: Provider org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
        at org.eclipse.jetty.util.ServiceLoaderSpliterator.tryAdvance(ServiceLoaderSpliterator.java:39)
        ... 18 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/util/StaticException
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.<init>(PerMessageDeflateExtension.java:67)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
        ... 21 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.StaticException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 27 more
```
---

## Expected Behavior

No error messages about a missing class and working transcriptions.

---

## Possible Solution

When taking a look into the bundled libraries, jetty 11.0.9 is bundled. Somehow the class `StaticException` was introduced in jetty version 11.0.10. 

Trying to verify, if the class exist, on a local installation results in the same behavior. Even if the jetty version is set to 11.0.10 in jigasis pom.xml, jetty version 11.0.9 will be bundled because of jicoco.

Therefore jicoco should be updated to a version, which uses jetty in version 11.0.10.

---

**Comment by lukasstoecklein** [comment]
I went a step further and rebuilt Jigasi except in the pom.xml I replaced
`<jicoco.version>1.1-107-gfb316f8</jicoco.version>`
with
`<jicoco.version>1.1-112-g46bbe5c</jicoco.version>`
which is the nearest version that uses jetty 11.0.10. As you can see here https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/org/jitsi/jicoco

However I'm then hit with this error

```
2023-03-18 19:35:39.200 INFO: [25] CallControlMucActivator.joinCommonRoom#283: Joining call control room: JigasiBrewery@internal.auth.jigasi.myapp.com pps:ProtocolProviderServiceJabberImpl(Jabber:jigasi@auth.jigasi.myapp.com), id:acc-xmpp-1
2023-03-18 19:35:39.321 INFO: [40] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$MemberListener.joined: jigasibrewery@internal.auth.jigasi.myapp.com/jitsi-26u9o6s has joined the jigasibrewery@internal.auth.jigasi.myapp.com chat room.
2023-03-18 19:35:39.348 INFO: [25] CallControlMucActivator.joinCommonRoom#321: Joined call control room: JigasiBrewery@internal.auth.jigasi.myapp.com pps:ProtocolProviderServiceJabberImpl(Jabber:jigasi@auth.jigasi.myapp.com), id:acc-xmpp-1 nickname:jitsi-26u9o6s sessionId:null
2023-03-18 19:35:39.353 WARNING: [31] org.jivesoftware.smackx.xdata.provider.DataFormProvider.parseField: Unknown form field child element {jabber:x:data}desc ignored
2023-03-18 19:35:39.412 WARNING: [31] org.jivesoftware.smack.parsing.ExceptionThrowingCallbackWithHint.handleUnparsableStanza: Parsing exception "javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,3722]
Message: found: CHARACTERS, expected START_ELEMENT or END_ELEMENT" encountered. This exception will be re-thrown, leading to a disconnect. You can change this behavior by setting a different ParsingExceptionCallback using setParsingExceptionCallback(). More information an be found in AbstractXMPPConnection's javadoc.
2023-03-18 19:35:39.427 SEVERE: [38] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$ChatRoomPresenceListener.processOwnPresence: Failed to send config form.
org.jivesoftware.smack.SmackException$NotConnectedException: The connection XMPPTCPConnection[jigasi@auth.jigasi.myapp.com/jitsi-26u9o6s] (0) is no longer connected while waiting for response with IQReplyFilter: iqAndIdFilter (AndFilter: (OrFilter: (IQTypeFilter: type=error, IQTypeFilter: type=result), StanzaIdFilter: id=UFVUE-7)), : fromFilter (OrFilter: (FromMatchesFilter (full): jigasibrewery@internal.auth.jigasi.myapp.com)) because of java.io.IOException: org.jivesoftware.smack.xml.XmlPullParserException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,3722]
Message: found: CHARACTERS, expected START_ELEMENT or END_ELEMENT
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:276)
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:228)
	at org.jivesoftware.smackx.muc.MultiUserChat.getConfigurationForm(MultiUserChat.java:844)
	at net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$ChatRoomPresenceListener.processOwnPresence(ChatRoomJabberImpl.java:3379)
	at net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$ChatRoomPresenceListener.processStanza(ChatRoomJabberImpl.java:3352)
	at org.jivesoftware.smack.AbstractXMPPConnection$4.run(AbstractXMPPConnection.java:1601)
	at org.jivesoftware.smack.AbstractXMPPConnection$10.run(AbstractXMPPConnection.java:2146)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: org.jivesoftware.smack.xml.XmlPullParserException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,3722]
Message: found: CHARACTERS, expected START_ELEMENT or END_ELEMENT
	at org.jivesoftware.smack.parsing.ExceptionThrowingCallback.handleUnparsableStanza(ExceptionThrowingCallback.java:36)
	at org.jivesoftware.smack.parsing.ExceptionThrowingCallbackWithHint.handleUnparsableStanza(ExceptionThrowingCallbackWithHint.java:42)
	at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:1458)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1000(XMPPTCPConnection.java:131)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:972)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
	... 1 more
Caused by: org.jivesoftware.smack.xml.XmlPullParserException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,3722]
Message: found: CHARACTERS, expected START_ELEMENT or END_ELEMENT
	at org.jivesoftware.smack.xml.stax.StaxXmlPullParser.nextTag(StaxXmlPullParser.java:235)
	at org.jivesoftware.smackx.xdata.provider.DataFormProvider.parseField(DataFormProvider.java:199)
	at org.jivesoftware.smackx.xdata.provider.DataFormProvider.parseField(DataFormProvider.java:144)
	at org.jivesoftware.smackx.xdata.provider.DataFormProvider.parse(DataFormProvider.java:92)
	at org.jivesoftware.smackx.xdata.provider.DataFormProvider.parse(DataFormProvider.java:61)
	at org.jivesoftware.smack.provider.Provider.parse(Provider.java:53)
	at org.jivesoftware.smack.util.PacketParserUtils.parseExtensionElement(PacketParserUtils.java:840)
	at org.jivesoftware.smack.util.PacketParserUtils.addExtensionElement(PacketParserUtils.java:928)
	at org.jivesoftware.smack.util.PacketParserUtils.addExtensionElement(PacketParserUtils.java:923)
	at org.jivesoftware.smackx.muc.provider.MUCOwnerProvider.parse(MUCOwnerProvider.java:53)
	at org.jivesoftware.smackx.muc.provider.MUCOwnerProvider.parse(MUCOwnerProvider.java:36)
	at org.jivesoftware.smack.provider.IQProvider.parse(IQProvider.java:64)
	at org.jivesoftware.smack.provider.IqProvider.parse(IqProvider.java:40)
	at org.jivesoftware.smack.util.PacketParserUtils.parseIQ(PacketParserUtils.java:555)
	at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:113)
	at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:1450)
	... 5 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,3722]
Message: found: CHARACTERS, expected START_ELEMENT or END_ELEMENT
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.nextTag(XMLStreamReaderImpl.java:1361)
	at org.jivesoftware.smack.xml.stax.StaxXmlPullParser.nextTag(StaxXmlPullParser.java:233)
	... 20 more
```

It smells to me like it's because of a library version mismatch. I'm curious, does anyone actually have transcription working in any configuration (Google or Vosk)?

**Comment by dj95** [comment]
@lukasstoecklein We've tried to inject just the missing jar file into jigasi and it started working, but IMHO it's just dirty hack for debugging and trying if the remaining setup works.

Either way, the transcription feature started working with vosk under the hack. Translations however did not work. Jigasi sends the request to libretranslate, which seems to answer correctly (at least according to Wireshark), but it somehow gets lost on the way back to the browser.

**Comment by damencho** [comment]
> It smells to me like it's because of a library version mismatch. I'm curious, does anyone actually have transcription working in any configuration (Google or Vosk)?

Yep, the latest version with running Google transcriptions is used for jaas.

**Comment by SkyTaurus** [comment]
Add to /usr/share/jigasi/lib
wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/11.0.10/jetty-util-11.0.10.jar
