### ISSUE TITLE
VOSK with different languages

### ISSUE THREAD

**Issue by SkyTaurus** [jitsi/jigasi#481]
I have jitsi 8319 and try to use VOSK
jigasi version 1.1-288-gccf44d7 (from pom.xml)

if I use one language I set in jigasi
`org.jitsi.jigasi.transcription.vosk.websocket_url=ws://172.17.0.15:2700`

and it works fine, but if I add another language and change config to
`org.jitsi.jigasi.transcription.vosk.websocket_url={“en”: “ws://172.17.0.15:2700”, “ru”: “ws://172.17.0.16:2710”}`
I got error in Jigasi

`May  2 11:01:02  jigasi[872]: Caused by: java.lang.ClassCastException: class org.json.simple.JSONObject cannot be cast to class org.json.JSONObject (org.json.simple.JSONObject and org.json.JSONObject are in unnamed module of loader 'app')
May  2 11:01:02  jigasi[872]: 	at org.jitsi.jigasi.transcription.VoskTranscriptionService.generateWebsocketUrl(VoskTranscriptionService.java:91)
May  2 11:01:02 jigasi[872]: 	at org.jitsi.jigasi.transcription.VoskTranscriptionService.initStreamingSession(VoskTranscriptionService.java:169)
May  2 11:01:02  jigasi[872]: 	... 11 more
May  2 11:01:19  jigasi[872]: May 02, 2023 11:01:19 AM org.jitsi.utils.logging.LoggerImpl log`

@nshmyrev Please take a look

**Comment by nshmyrev** [comment]
You can not config like this I suppose, you need multilingual models instead (ru+en).

**Comment by SkyTaurus** [comment]
From Readme

If you have multiple instances of VOSK for transcribing different languages, configure the URLs of different VOSK instances in JSON format:

`# org.jitsi.jigasi.transcription.vosk.websocket_url={"en": "ws://localhost:2700", "fr": "ws://localhost:2710"}`


In this case, this is what I need

**Comment by nshmyrev** [comment]
Thank you for the patch!

**Comment by SkyTaurus** [comment]
I checked and it works great.
But after building the container (or when I take it ready from dockerhub), I have to add the library  [jetty-util-11.0.10.jar](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/11.0.10/jetty-util-11.0.10.jar) because of an error https://github.com/jitsi/jigasi/issues/472. Could you also fix it?

And one more thing I noticed -  VOSK container on another port does not work as it is written in the documentation.
If I run as in README
`docker run -d -p 2710:2700 alphacep/kaldi-en:latest`
I cannot connect from jigasi to port 2710 , but if I run as 
`docker run  -p 2710:2710 --env VOSK_SERVER_PORT=2710 alphacep/kaldi-en:latest` it works fine.
With default port works fine
`docker run -d -p 2700:2700 alphacep/kaldi-en:latest`
Need to fix README?

**Comment by nshmyrev** [comment]
It should be 2700:2710 instead

**Comment by SkyTaurus** [comment]
I need to run 2 container
first
 `docker run -d -p 2700:2700 alphacep/kaldi-en:latest`  - works fine

second 
`docker run -d -p 2720:2700 alphacep/kaldi-ru:latest`    - doesn't work - jigasi cannot connect
if I try
`docker run  -p 2720:2720 --env VOSK_SERVER_PORT=2720 alphacep/kaldi-en:latest
`    - works fine

**Comment by damencho** [comment]
I think all these issues are fixed now, please test the latest unstable version of jigasi.

If you agree on the docker command parameters, please open a PR in the README fixing it.

**Comment by Strouroul** [comment]
i have this here

 org.jitsi.jigasi.transcription.vosk.websocket_url={"zh": "ws://localhost:2701","zh-CN": "ws://localhost:2701","zh-cn": "ws://localhost:2701" ,"zh_CN": "ws://localhost:2701" , "zhCN": "ws://localhost:2701",  "en": "ws://localhost:2700"}

but ONLY the english works


but the other contains works fine and i can connect to them anyways 

the latest Jigasi wont connect to any other ones except the en

c3e634083508   alphacep/kaldi-cn:latest        "python3 ./asr_serve…"   4 weeks ago   Up 12 seconds           0.0.0.0:2701->2700/tcp, [::]:2701->2700/tcp   charming_banach
184da621df6a   alphacep/kaldi-en:latest        "python3 ./asr_serve…"   4 weeks ago   Up Less than a second   0.0.0.0:2700->2700/tcp, [::]:2700->2700/tcp   great_leavitt
Jigasi Restarted

**Comment by damencho** [comment]
How are you changing the language? You need to do it either by changing the UI interface language or by setting https://github.com/jitsi/jitsi-meet/blob/078503b1b354635e4f9b2851dab7ebe4b68a881f/config.js#L488

**Comment by Strouroul** [comment]
> How are you changing the language? You need to do it either by changing the UI interface language or by setting https://github.com/jitsi/jitsi-meet/blob/078503b1b354635e4f9b2851dab7ebe4b68a881f/config.js#L488


i am changing the language from the UI

but for some reason the english works fine but not another language like (chinese)

the subtitles shows in English even if i choose any other language

and the transcript is ONLY saved in English and not other languages 

it would show subtitles and save the lang in another language when i ONLY do this here in the sip-communicator.properties


 org.jitsi.jigasi.transcription.vosk.websocket_url=ws://localhost:2701


but when i add 2 or more languages ONLY the english one works

 org.jitsi.jigasi.transcription.vosk.websocket_url={"zh": "ws://localhost:2701", "en": "ws://localhost:2700"}


by the way the locations work fine and i can connect to those ws at those addresses without any issues

and when i put just the 1 location it works fine without issues

but i want to be able to add multiple websocket_urls !!


sometimes when i add the 2 URLs the Chinese subtitles show BUT only after the English ones shows 1st , plus the transcript is never saved in any other languages even if i choose Chinese from the UI

**Comment by damencho** [comment]
You are setting translated languages, for those you need to set up google translate for example and you need to choose translation language from the menu with subtitles languages. And then transcribing in English will be stored as English and final transcriptions will be translated via the translated service and will be sent to users.

For the transcriber language you either set `preferredLanguage` or you change the UI language.
