### ISSUE TITLE
XMPPBOSHConnection[not-authenticated] (4) was not authenticated

### ISSUE THREAD

**Issue by doduclong** [jitsi/jigasi#540]
Hi,
I have installed jigasi and jitsi meet but when I turn on subtitles and speak, no subtitles are displayed. I use Vosk to transcription.
I followed the instructions below: https://medium.com/@sirHC77/enabling-transcription-in-jitsi-meet-a56cc4dbda18
Below is the system log, please check for me. Thanks!

**jigasi.log**
java.lang.Exception: Fail to join muc!
        at org.jitsi.jigasi.xmpp.CallControlMucActivator$WaitToJoinRoom.waitToJoinRoom(CallControlMucActivator.java:739)
        at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.setDialResponseAndRegisterHangUpHandler(CallControlMucActivator.java:674)
        at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.processIQInternal(CallControlMucActivator.java:631)
        at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.lambda$processIQ$0(CallControlMucActivator.java:588)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-06-24 08:36:28.019 WARNING: [12] org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary: XMPPBOSHConnection[not-authenticated] (4) was not authenticated

**jicofo.log**
Jicofo 2024-06-24 08:36:18.021 INFO: [53] [room=sdfd@conference.meet.cmcati.com meeting_id=19fa2817-578c-4cd5-a7ee-6ecb8f161504] TranscriberManager.selectTranscriber#195: Attempting to invite transcriber
Jicofo 2024-06-24 08:36:18.021 WARNING: [53] [room=sdfd@conference.meet.cmcati.com meeting_id=19fa2817-578c-4cd5-a7ee-6ecb8f161504] TranscriberManager.selectTranscriber#201: Unable to invite transcriber due to no Jigasi instances being available

**docker log**
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:11:12:13:14:15
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:ReadDataFiles():model.cc:249) Loading i-vector extractor from /opt/vosk-model-en/model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:282) Loading HCLG from /opt/vosk-model-en/model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:300) Loading words from /opt/vosk-model-en/model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:311) Loading winfo /opt/vosk-model-en/model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:318) Loading subtract G.fst model from /opt/vosk-model-en/model/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:320) Loading CARPA model from /opt/vosk-model-en/model/rescore/G.carpa
LOG (VoskAPI:ReadDataFiles():model.cc:326) Loading RNNLM model from /opt/vosk-model-en/model/rnnlm/final.raw

**Comment by damencho** [comment]
Have you created a transcriber user, normally using the recording domain used for jibri and have you set it up in jigasi config?
https://github.com/jitsi/jigasi/blob/7a3211b5ccc127db6bb7c2032cd6937d8fb5dce5/jigasi-home/sip-communicator.properties#L168

**Comment by doduclong** [comment]
> Have you created a transcriber user, normally using the recording domain used for jibri and have you set it up in jigasi config?
> 
> https://github.com/jitsi/jigasi/blob/7a3211b5ccc127db6bb7c2032cd6937d8fb5dce5/jigasi-home/sip-communicator.properties#L168

How do I register that account?

**Comment by damencho** [comment]
Similar to the jibri one,. check its instructions 
https://github.com/jitsi/jibri?tab=readme-ov-file#prosody

**Comment by doduclong** [comment]
> Similar to the jibri one,. check its instructions https://github.com/jitsi/jibri?tab=readme-ov-file#prosody

Thank you

**Comment by doduclong** [comment]
> Similar to the jibri one,. check its instructions https://github.com/jitsi/jibri?tab=readme-ov-file#prosody

Using a SIP account is required for use Transcription feature? Can I use SIP account(test@sip2sip.info)? If not, can you give me the address to register for a SIP account?

**Comment by damencho** [comment]
Nope, you don't need a sip account.

**Comment by bmilde** [comment]
I'm also getting this authentication error, when I try to turn on the subtitles in a meeting:

```
2024-07-27 00:47:21.220 INFO: [45] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$MemberListener.joined: jigasibrewery@internal.auth.meet.replaceforprivacy.com/focus has joined the jigasibrewery@internal.auth.meet.replaceforprivacy.com chat room.
2024-07-27 00:47:21.243 INFO: [48] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$MemberListener.joined: jigasibrewery@internal.auth.meet.replaceforprivacy.com/jitsi-274018t has joined the jigasibrewery@internal.auth.meet.replaceforprivacy.com chat room.
2024-07-27 00:47:21.299 INFO: [39] CallControlMucActivator.joinCommonRoom#327: Joined call control room: JigasiBrewery@internal.auth.meet.replaceforprivacy.com pps:ProtocolProviderServiceJabberImpl(Jabber:recorder@meet.replaceforprivacy.com), id:acc-xmpp-1 nickname:jitsi-274018t sessionId:null
2024-07-27 00:48:20.334 INFO: [39] CallControl.handleDialIq#201: [ctx=17220341003071721872815] Got dial request null -> jitsi_meet_transcribe room: ben@conference.meet.replaceforprivacy.com
2024-07-27 00:48:20.561 INFO: [39] JvbConference.start#529: [ctx=17220341003071721872815] Starting JVB conference room: ben@conference.meet.replaceforprivacy.com
2024-07-27 00:48:20.568 INFO: [39] JvbConference.createAccountPropertiesForCallId#1871: [ctx=17220341003071721872815] Using bosh url:https://meet.replaceforprivacy.com/http-bind?room=ben
2024-07-27 00:48:20.592 INFO: [39] JvbConference.setXmppProvider#669: [ctx=17220341003071721872815] Using ProtocolProviderServiceJabberImpl(Jabber:recorder@meet.replaceforprivacy.com/06e3ec45)
2024-07-27 00:48:20.710 INFO: [53] org.igniterealtime.jbosh.BOSHClient.init: Starting with 1 request processors
2024-07-27 00:48:20.960 INFO: [53] net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged: Jingle : ON
2024-07-27 00:48:20.963 INFO: [57] JvbConference.registrationStateChangedInternal#730: [ctx=17220341003071721872815] Registering XMPP.
2024-07-27 00:48:21.019 SEVERE: [53] net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin: Failed to connect to XMPP service for:ProtocolProviderServiceJabberImpl(Jabber:recorder@meet.replaceforprivacy.com/06e3ec45)
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
        at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:286)
        at org.jivesoftware.smack.AbstractXMPPConnection.lambda$new$2(AbstractXMPPConnection.java:406)
        at org.jivesoftware.smack.NonzaCallback$ClassAndConsumer.accept(NonzaCallback.java:177)
        at org.jivesoftware.smack.NonzaCallback$ClassAndConsumer.access$200(NonzaCallback.java:166)
        at org.jivesoftware.smack.NonzaCallback.onNonzaReceived(NonzaCallback.java:46)
        at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessNonza(AbstractXMPPConnection.java:1439)
        at org.jivesoftware.smack.bosh.XMPPBOSHConnection.access$1800(XMPPBOSHConnection.java:69)
        at org.jivesoftware.smack.bosh.XMPPBOSHConnection$BOSHPacketReader.responseReceived(XMPPBOSHConnection.java:538)
        at org.igniterealtime.jbosh.BOSHClient.fireResponseReceived(BOSHClient.java:1610)
        at org.igniterealtime.jbosh.BOSHClient.processExchange(BOSHClient.java:1145)
        at org.igniterealtime.jbosh.BOSHClient.processMessages(BOSHClient.java:999)
        at org.igniterealtime.jbosh.BOSHClient.access$300(BOSHClient.java:100)
        at org.igniterealtime.jbosh.BOSHClient$RequestProcessor.run(BOSHClient.java:1728)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-07-27 00:48:21.049 SEVERE: [57] JvbConference.registrationStateChangedInternal#734: [ctx=17220341003071721872815] XMPP Connection failed. RegistrationStateChangeEvent[ oldState=Registering; newState=RegistrationState=Connection Failed; userRequest=false; reasonCode=6; reason=SASLError using SCRAM-SHA-1: not-authorized]
```

It also not clear what reasonCode=6 is supposed to mean, I find no errors in prosody.err and prosody.log.

In /etc/jitsi/jigasi/sip-communicator.properties I have set up all xmpp user configs and created a new account with prosodyctl:

```
prosodyctl register recorder meet.replaceforprivacy.com mypasswordincleartext
```

```
org.jitsi.jigasi.ENABLE_SIP=false
org.jitsi.jigasi.ENABLE_TRANSCRIPTION=true
org.jitsi.jigasi.transcription.customService=org.jitsi.jigasi.transcription.VoskTranscriptionService
org.jitsi.jigasi.transcription.vosk.websocket_url=ws://localhost:2700
...
net.java.sip.communicator.impl.protocol.jabber.acc-xmpp-1.ACCOUNT_UID=Jabber:recorder@meet.replaceforprivacy.com
net.java.sip.communicator.impl.protocol.jabber.acc-xmpp-1.USER_ID=recorder@meet.replaceforprivacy.com
net.java.sip.communicator.impl.protocol.jabber.acc-xmpp-1.IS_SERVER_OVERRIDDEN=true
net.java.sip.communicator.impl.protocol.jabber.acc-xmpp-1.SERVER_ADDRESS=127.0.0.1
net.java.sip.communicator.impl.protocol.jabber.acc-xmpp-1.SERVER_PORT=5222
net.java.sip.communicator.impl.protocol.jabber.acc-xmpp-1.PASSWORD=<base encoded pw>
...
org.jitsi.jigasi.xmpp.acc.USER_ID=recorder@meet.replaceforprivacy.com # I tried many different accounts
org.jitsi.jigasi.xmpp.acc.PASS= <I tried base encoded and clear text>
org.jitsi.jigasi.xmpp.acc.ANONYMOUS_AUTH=false
```

It would be nice if README.md would contain some pointers on how to do authentication correctly in the config. Because right now there is no mention of setting up a dedicated account like "recorder" for jigasi (like there is for jibri).

**Comment by KCS-Mack** [comment]
Was this issue ever fixed?  I followed the tutorials, but still getting:

TranscriberManager.selectTranscriber#201: Unable to invite transcriber due to no Jigasi instances being available

I checked systemd, Jigasi is running fine, not sure what else I need to do.

**Comment by damencho** [comment]
> I checked systemd, Jigasi is running fine, not sure what else I need to do.

There is no issue with jigasi to be foxed, this is about its configuration.
What do you see in jigasi logs?

**Comment by KCS-Mack** [comment]
Here are the logs from Jigasi, any idea what is wrong?


2024-09-06 07:00:18.694 SEVERE: [2945] net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin: Failed to connect to XMPP service for:ProtocolProviderServiceJabberImpl(Jabber:40223562@meet.HIDDEN.com/40223562)
org.jivesoftware.smack.SmackException$SmackSaslException: No supported and enabled SASL Mechanism provided by server. Server announced mechanisms: [SCRAM-SHA-1, SCRAM-SHA-256, PLAIN]. Registered SASL mechanisms with Smack: [SASL Mech: GSSAPI, Prio: 100, SASL Mech: SCRAM-SHA-1-PLUS, Prio: 100, SASL Mech: SCRAM-SHA-1, Prio: 110, SASL Mech: DIGEST-MD5, Prio: 200, SASL Mech: CRAM-MD5, Prio: 300, SASL Mech: PLAIN, Prio: 400, SASL Mech: X-OAUTH2, Prio: 410, SASL Mech: EXTERNAL, Prio: 500, SASL Mech: ANONYMOUS, Prio: 500]. Enabled SASL mechanisms for this connection: [ANONYMOUS]. Blacklisted SASL mechanisms: [SCRAM-SHA-1-PLUS]. Skip reasons: []
	at org.jivesoftware.smack.SASLAuthentication.selectMechanism(SASLAuthentication.java:366)
	at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:188)
	at org.jivesoftware.smack.AbstractXMPPConnection.authenticate(AbstractXMPPConnection.java:896)
	at org.jivesoftware.smack.bosh.XMPPBOSHConnection.loginInternal(XMPPBOSHConnection.java:231)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:637)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:594)
	at net.java.sip.communicator.impl.protocol.jabber.AnonymousLoginStrategy.login(AnonymousLoginStrategy.java:83)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1369)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:967)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:792)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:494)
	at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)
2024-09-06 07:00:18.696 SEVERE: [2945] net.java.sip.communicator.util.UtilActivator.uncaughtException: An uncaught exception occurred in thread=Thread[Thread-2924,5,main], and message was: null
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
	at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.removeNodeInformationProvider(ServiceDiscoveryManager.java:387)
	at net.java.sip.communicator.impl.protocol.jabber.ScServiceDiscoveryManager.stop(ScServiceDiscoveryManager.java:680)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.disconnectAndCleanConnection(ProtocolProviderServiceJabberImpl.java:1529)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1004)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:792)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:494)
	at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)

**Comment by bmilde** [comment]
Just a FYI, on my end this is purely a BOSH authentication issue. Using jigasi with a jitsi server with anonymous authentication works. Obviously this isn't really an option if you run it publicly. I had SIP diabled with the anonymous server too, so that isn't the issue.

**Comment by damencho** [comment]
Have you tried this prop
https://github.com/jitsi/jigasi/blob/c53ba860ae9073bc4ac6bbd4ab2fd9299737c835/jigasi-home/sip-communicator.properties#L173

**Comment by KCS-Mack** [comment]
> Have you tried this prop
> 
> https://github.com/jitsi/jigasi/blob/c53ba860ae9073bc4ac6bbd4ab2fd9299737c835/jigasi-home/sip-communicator.properties#L173

That seemed to get me to the next step... however now I am getting other errros

2024-09-06 12:05:54.604 SEVERE: [37] CallControlMucActivator$DialIqHandler.processIQInternal#642: [ctx=17256243445901746112737] Error processing RayoIq
java.lang.Exception: Fail to join muc!
	at org.jitsi.jigasi.xmpp.CallControlMucActivator$WaitToJoinRoom.waitToJoinRoom(CallControlMucActivator.java:739)
	at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.setDialResponseAndRegisterHangUpHandler(CallControlMucActivator.java:674)
	at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.processIQInternal(CallControlMucActivator.java:631)
	at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.lambda$processIQ$0(CallControlMucActivator.java:588)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-09-06 12:06:46.344 INFO: [37] CallControl.handleDialIq#201: [ctx=1725624406330705740225] Got dial request null -> jitsi_meet_transcribe room: welcomereserveslosebehind@conference.meet.kryptstar.com
2024-09-06 12:06:46.354 INFO: [37] JvbConference.start#529: [ctx=1725624406330705740225] Starting JVB conference room: welcomereserveslosebehind@conference.meet.kryptstar.com
2024-09-06 12:06:46.361 INFO: [37] JvbConference.createAccountPropertiesForCallId#1871: [ctx=1725624406330705740225] Using bosh url:https://meet.kryptstar.com/http-bind?room=welcomereserveslosebehind
2024-09-06 12:06:46.400 INFO: [37] JvbConference.setXmppProvider#669: [ctx=1725624406330705740225] Using ProtocolProviderServiceJabberImpl(Jabber:33bdc116@meet.kryptstar.com/33bdc116)
2024-09-06 12:06:46.422 INFO: [79] org.igniterealtime.jbosh.BOSHClient.init: Starting with 1 request processors
2024-09-06 12:06:46.491 INFO: [79] net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged: Jingle : ON
2024-09-06 12:06:46.492 INFO: [55] JvbConference.registrationStateChangedInternal#730: [ctx=1725624406330705740225] Registering XMPP.
2024-09-06 12:06:46.492 SEVERE: [79] net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin: Failed to connect to XMPP service for:ProtocolProviderServiceJabberImpl(Jabber:33bdc116@meet.kryptstar.com/33bdc116)
org.jivesoftware.smack.SmackException$SmackSaslException: No supported and enabled SASL Mechanism provided by server. Server announced mechanisms: [SCRAM-SHA-256, PLAIN, SCRAM-SHA-1]. Registered SASL mechanisms with Smack: [SASL Mech: GSSAPI, Prio: 100, SASL Mech: SCRAM-SHA-1-PLUS, Prio: 100, SASL Mech: SCRAM-SHA-1, Prio: 110, SASL Mech: DIGEST-MD5, Prio: 200, SASL Mech: CRAM-MD5, Prio: 300, SASL Mech: PLAIN, Prio: 400, SASL Mech: X-OAUTH2, Prio: 410, SASL Mech: EXTERNAL, Prio: 500, SASL Mech: ANONYMOUS, Prio: 500]. Enabled SASL mechanisms for this connection: [ANONYMOUS]. Blacklisted SASL mechanisms: [SCRAM-SHA-1-PLUS]. Skip reasons: []
	at org.jivesoftware.smack.SASLAuthentication.selectMechanism(SASLAuthentication.java:366)
	at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:188)
	at org.jivesoftware.smack.AbstractXMPPConnection.authenticate(AbstractXMPPConnection.java:896)
	at org.jivesoftware.smack.bosh.XMPPBOSHConnection.loginInternal(XMPPBOSHConnection.java:231)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:637)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:594)
	at net.java.sip.communicator.impl.protocol.jabber.AnonymousLoginStrategy.login(AnonymousLoginStrategy.java:83)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1369)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:967)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:792)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:494)
	at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)
2024-09-06 12:06:46.501 SEVERE: [79] net.java.sip.communicator.util.UtilActivator.uncaughtException: An uncaught exception occurred in thread=Thread[Thread-56,5,main], and message was: null
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
	at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.removeNodeInformationProvider(ServiceDiscoveryManager.java:387)
	at net.java.sip.communicator.impl.protocol.jabber.ScServiceDiscoveryManager.stop(ScServiceDiscoveryManager.java:680)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.disconnectAndCleanConnection(ProtocolProviderServiceJabberImpl.java:1529)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1004)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:792)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:494)
	at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)
	
	
	

Any idea?

**Comment by KCS-Mack** [comment]
> Just a FYI, on my end this is purely a BOSH authentication issue. Using jigasi with a jitsi server that has anonymous authentication works. Obviously this isn't really an option if you run it publicly. I had SIP diabled with the anonymous server too, so that isn't the issue.

Thank you, I'll keep that in mind as an option.

**Comment by KCS-Mack** [comment]
> You are trying the transcriber, have you setup its authentication to the recorder domain and so on ...

no... i was looking for instructions on that, but it seems like there is a gap in the documentation?  So we have to completely do the recorder auth first, then do the transcriber?

If you happen to have a link to the full tutorial I would be really grateful 🙇

**Comment by damencho** [comment]
> Similar to the jibri one,. check its instructions
> https://github.com/jitsi/jibri?tab=readme-ov-file#prosody

Try this. I will try updating the jigasi docs the following months when I have time.

**Comment by QinjieXiao** [comment]
> Hi, I have installed jigasi and jitsi meet but when I turn on subtitles and speak, no subtitles are displayed. I use Vosk to transcription. I followed the instructions below: https://medium.com/@sirHC77/enabling-transcription-in-jitsi-meet-a56cc4dbda18 Below is the system log, please check for me. Thanks!
> 
> **jigasi.log** java.lang.Exception: Fail to join muc! at org.jitsi.jigasi.xmpp.CallControlMucActivator$WaitToJoinRoom.waitToJoinRoom(CallControlMucActivator.java:739) at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.setDialResponseAndRegisterHangUpHandler(CallControlMucActivator.java:674) at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.processIQInternal(CallControlMucActivator.java:631) at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.lambda$processIQ$0(CallControlMucActivator.java:588) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) 2024-06-24 08:36:28.019 WARNING: [12] org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary: XMPPBOSHConnection[not-authenticated] (4) was not authenticated
> 
> **jicofo.log** Jicofo 2024-06-24 08:36:18.021 INFO: [53] [room=[sdfd@conference.meet.cmcati.com](mailto:sdfd@conference.meet.cmcati.com) meeting_id=19fa2817-578c-4cd5-a7ee-6ecb8f161504] TranscriberManager.selectTranscriber#195: Attempting to invite transcriber Jicofo 2024-06-24 08:36:18.021 WARNING: [53] [room=[sdfd@conference.meet.cmcati.com](mailto:sdfd@conference.meet.cmcati.com) meeting_id=19fa2817-578c-4cd5-a7ee-6ecb8f161504] TranscriberManager.selectTranscriber#201: Unable to invite transcriber due to no Jigasi instances being available
> 
> **docker log** LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6 LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:11:12:13:14:15 LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes. LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components. LOG (VoskAPI:ReadDataFiles():model.cc:249) Loading i-vector extractor from /opt/vosk-model-en/model/ivector/final.ie LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done. LOG (VoskAPI:ReadDataFiles():model.cc:282) Loading HCLG from /opt/vosk-model-en/model/graph/HCLG.fst LOG (VoskAPI:ReadDataFiles():model.cc:300) Loading words from /opt/vosk-model-en/model/graph/words.txt LOG (VoskAPI:ReadDataFiles():model.cc:311) Loading winfo /opt/vosk-model-en/model/graph/phones/word_boundary.int LOG (VoskAPI:ReadDataFiles():model.cc:318) Loading subtract G.fst model from /opt/vosk-model-en/model/rescore/G.fst LOG (VoskAPI:ReadDataFiles():model.cc:320) Loading CARPA model from /opt/vosk-model-en/model/rescore/G.carpa LOG (VoskAPI:ReadDataFiles():model.cc:326) Loading RNNLM model from /opt/vosk-model-en/model/rnnlm/final.raw

Hi, have you solve the issue?

**Comment by KCS-Mack** [comment]
Sorry no I will check tomorrow though Sent from my iPhoneOn Sep 8, 2024, at 6:48 PM, QinjieXiao ***@***.***> wrote:﻿

Hi, I have installed jigasi and jitsi meet but when I turn on subtitles and speak, no subtitles are displayed. I use Vosk to transcription. I followed the instructions below: ***@***.***/enabling-transcription-in-jitsi-meet-a56cc4dbda18 Below is the system log, please check for me. Thanks!
jigasi.log java.lang.Exception: Fail to join muc! at org.jitsi.jigasi.xmpp.CallControlMucActivator$WaitToJoinRoom.waitToJoinRoom(CallControlMucActivator.java:739) at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.setDialResponseAndRegisterHangUpHandler(CallControlMucActivator.java:674) at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.processIQInternal(CallControlMucActivator.java:631) at org.jitsi.jigasi.xmpp.CallControlMucActivator$DialIqHandler.lambda$processIQ$0(CallControlMucActivator.java:588) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) 2024-06-24 08:36:28.019 WARNING: [12] org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary: XMPPBOSHConnection[not-authenticated] (4) was not authenticated
jicofo.log Jicofo 2024-06-24 08:36:18.021 INFO: [53] ***@***.*** meeting_id=19fa2817-578c-4cd5-a7ee-6ecb8f161504] TranscriberManager.selectTranscriber#195: Attempting to invite transcriber Jicofo 2024-06-24 08:36:18.021 WARNING: [53] ***@***.*** meeting_id=19fa2817-578c-4cd5-a7ee-6ecb8f161504] TranscriberManager.selectTranscriber#201: Unable to invite transcriber due to no Jigasi instances being available
docker log LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6 LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:11:12:13:14:15 LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes. LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components. LOG (VoskAPI:ReadDataFiles():model.cc:249) Loading i-vector extractor from /opt/vosk-model-en/model/ivector/final.ie LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done. LOG (VoskAPI:ReadDataFiles():model.cc:282) Loading HCLG from /opt/vosk-model-en/model/graph/HCLG.fst LOG (VoskAPI:ReadDataFiles():model.cc:300) Loading words from /opt/vosk-model-en/model/graph/words.txt LOG (VoskAPI:ReadDataFiles():model.cc:311) Loading winfo /opt/vosk-model-en/model/graph/phones/word_boundary.int LOG (VoskAPI:ReadDataFiles():model.cc:318) Loading subtract G.fst model from /opt/vosk-model-en/model/rescore/G.fst LOG (VoskAPI:ReadDataFiles():model.cc:320) Loading CARPA model from /opt/vosk-model-en/model/rescore/G.carpa LOG (VoskAPI:ReadDataFiles():model.cc:326) Loading RNNLM model from /opt/vosk-model-en/model/rnnlm/final.raw

Hi, have you solve the issue?

**Comment by pallavi199427** [comment]
+1 for same error
