### ISSUE TITLE
PulseAudioRenderer dependency

### ISSUE THREAD

**Issue by rasos** [jitsi/jigasi#66]
After adding Jigasi from the stable repo, the Jitsi meet home screen remains grey.
Jigasi seems to look for an audio device, but this is a headless Debian server.
Even after installing alsa-utils and pulseaudio packages still getting the exception.
This dependency should have been already fixed: http://lists.jitsi.org/pipermail/commits/2015-October/015591.html

`2017-08-03 21:21:59.485 SEVERE: [10] org.jitsi.impl.neomedia.device.DeviceConfiguration.log() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer with JMF.
java.lang.IllegalStateException: audioSystem
        at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:155)
        at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:135)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1046)
        at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:365)
        at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:160)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.initializeService(LibJitsiImpl.java:196)
        at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.getService(LibJitsiImpl.java:131)
        at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:91)
        at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:95)
        at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:172)
        at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:124)
        at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:391)
        at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:293)
        at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:460)
        at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:126)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:111)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:17)
        at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:220)
2017-08-03 21:21:59.509 INFO: [10] impl.neomedia.NeomediaActivator.start().542 Audio Notifier Service ...[REGISTERED]
`

**Comment by damencho** [comment]
These exceptions are harmless, ignore them. 
Are you able to make a normal conference on your deployment, with opening two tabs in chrome? 

If you see jitsi-meet grey screen means there is some issue with your jitsi-meet deployment before you even try contacting jigasi. Check js console logs, then jicofo logs.

**Comment by rasos** [comment]
Thank you for the hints. JS console said: 
`Uncaught ReferenceError: config is not defined
    at Object.<anonymous> (AuthHandler.js:16)
    at Object.defineProperty.value (app.bundle.min.js:32657)
    at t (bootstrap 33b51b1…:19)
    at Object.<anonymous> (connection.js:3)
    at Object.defineProperty.value (app.bundle.min.js:32191)
    at t (bootstrap 33b51b1…:19)
    at Object.<anonymous> (conference.js:4)
    at Object.defineProperty.value (app.bundle.min.js:75303)
    at t (bootstrap 33b51b1…:19)
    at Object.defineProperty.value (app.js:20)
    at t (bootstrap 33b51b1…:19)
    at Object.<anonymous> (app.bundle.min.js:58)
    at t (bootstrap 33b51b1…:19)
    at bootstrap 33b51b1…:39
    at bootstrap 33b51b1…:39
    at universalModuleDefinition:9
    at universalModuleDefinition:9`

Looking at  meet.fairchat.net-config.js revealed, that the syntax was wrong (missing `,` ). Fixed. 
Was definetely not a jigasi issue, was just triggered by a service restart and jicofo reading wrong config.
