### ISSUE TITLE
JNI error crash when attempting to run release 160

### ISSUE THREAD

**Issue by Ashaman-** [jitsi/jigasi#72]
CentOS7 x64, ejabberd 17.07.
`java -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)`

`./jigasi.sh --host=127.0.0.1 --domain=psyberia.im --subdomain=callcontrol --secret="hackme"
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/jitsi/xmpp/component/ComponentBase
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.jitsi.xmpp.component.ComponentBase
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more`

**Comment by damencho** [comment]
Try running:
`ant -lib ~/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3 copy-runtime-dependencies-from-maven`
Does this make any difference?
