### ISSUE TITLE
Problems with typical deployment which uses XMPP authentication

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jigasi#9]
There is no way to make Jigasi connect to anonymous domain in case our main domain requires authentication like described [here]. If we configure JVB_HOSTNAME to guest.jitsi-meet.example.com then component connection will fail. The only option is to configure user credentials for Jigasi and specify them in /usr/share/jitsi/jigasi/.sip-communicator/[sip-communicator.properties].
```
var config = {
    hosts: {
            domain: 'jitsi-meet.example.com',
            anonymousdomain: 'guest.jitsi-meet.example.com',
            ...
        },
        ...
}
```
[here]: https://github.com/jitsi/jicofo#secure-domain

[sip-communicator.properties]: https://github.com/jitsi/jigasi/blob/master/jigasi-home/sip-communicator.properties#L58

**Comment by satishdotpatel** [comment]
I did whatever you said and add account in sip-communicator.properties and getting following error

2015-04-18 23:37:41.678 SEVERE: [62] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register().462 Error registering
SASL authentication PLAIN failed: text:
        at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:341)
        at org.jivesoftware.smack.XMPPConnection.login(XMPPConnection.java:208)
        at net.java.sip.communicator.impl.protocol.jabber.LoginByPasswordStrategy.login(LoginByPasswordStrategy.java:143)
        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1285)
        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:933)
        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:744)
        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:457)
        at org.jitsi.jigasi.RegisterThread.run(RegisterThread.java:47)
2015-04-18 23:37:41.680 SEVERE: [62] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[Thread-45,10,main] and message was: No previous records found for account ID: Jabber:Extension 1003@prosody-softphone-dev1.example.com/Extension 1003 in packagenet.java.sip.communicator.impl.protocol.jabber
java.lang.IllegalArgumentException: No previous records found for account ID: Jabber:Extension 1003@prosody-softphone-dev1.example.com/Extension 1003 in packagenet.java.sip.communicator.impl.protocol.jabber
        at net.java.sip.communicator.service.protocol.ProtocolProviderFactory.storePassword(ProtocolProviderFactory.java:872)
        at net.java.sip.communicator.service.protocol.ProtocolProviderFactory.storePassword(ProtocolProviderFactory.java:825)
        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.fireRegistrationStateChanged(ProtocolProviderServiceJabberImpl.java:2081)
        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:466)
        at org.jitsi.jigasi.RegisterThread.run(RegisterThread.java:47)
2015-04-18 23:38:09.190 INFO: [78] org.jitsi.jigasi.GatewaySession.sipCallEnded().419 Sip call ended: Call: id=14319850600361259833588 peers=0
2015-04-18 23:38:09.191 INFO: [78] org.jitsi.jigasi.JvbConference.stop().454 14d68f5f981@callcontrol.prosody-softphone-dev1.example.com is removing account Jabber:Extension 1003@prosody-softphone-dev1.example.com/Extension 1003
2015-04-18 23:38:09.218 INFO: [78] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().114 Jingle : OFF
2015-04-18 23:38:09.219 INFO: [78] org.jitsi.jigasi.SipGateway.notifyCallEnded().193 Removed session for call 14d68f5f981@callcontrol.prosody-softphone-dev1.example.com
2015-04-18 23:38:09.221 INFO: [78] org.jitsi.jigasi.GatewaySession.peerStateChanged().653 null SIP peer state: Disconnected

**Comment by flantel** [comment]
I see this is still an issue. Anyone know how to solve it? I do not want my jigasi sip users to be seen as moderators.

**Comment by Ark74** [comment]
@satishdotpatel 
Maybe you have figure it out by now, but in case you haven't.
On the jigasi credentials the password should in plain text :confounded: as for now.
