### ISSUE TITLE
Exception after upgrade to jigasi 1.0-175

### ISSUE THREAD

**Issue by rasos** [jitsi/jigasi#90]
After upgrade on a Debian GNU/Linux 8.9 (jessie) we get: 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jitsi/jigasi/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

It was necessary to install openjdk-8 via backport due to an unmet dependency with ca-certificates-java https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851667

```
Start-Date: 2017-10-23  20:50:49
Commandline: apt install -t jessie-backports openjdk-8-jre-headless ca-certificates-java
Install: openjdk-8-jre-headless:amd64 (8u131-b11-1~bpo8+1)
Upgrade: ca-certificates-java:amd64 (20140324, 20161107~bpo8+1)
End-Date: 2017-10-23  20:51:09

Start-Date: 2017-10-23  20:51:31
Commandline: apt-get install openjdk-8-jre
Install: fonts-dejavu-extra:amd64 (2.34-1, automatic), libgif4:amd64 (4.1.6-11+deb8u1, automatic), libatk-wrapper-java:amd64 (0.30.5-1, automatic), libatk-wrapper-java-jni:amd64 (0.30.5-1, automatic), openjdk-8-jre:amd64 (8u131-b11-1~bpo8+1)
End-Date: 2017-10-23  20:51:43

Start-Date: 2017-10-23  20:51:58
Commandline: apt-get install jigasi
Upgrade: jigasi:amd64 (1.0-142, 1.0-175)
End-Date: 2017-10-23  20:52:26
```

Jigasi worked fine with the previous version.

**Comment by damencho** [comment]
Since build 149 jigasi requires java8, it will not run with java7. We are moving all projects to require java8.

**Comment by rasos** [comment]
Ah yes, after installing openjdk8 I forgot to switch manually Java versions with:
`update-alternatives --config java `
