### ISSUE TITLE
Error creating manager - no unix-java in java-library.path

### ISSUE THREAD

**Issue by dennishenry** [jitsi/jigasi#96]
I've banged my head against this for awhile now, so I'm resorting to reaching out for help. I'm having a really rough time getting jigasi to work on my CentOS Jitsi box, connecting to my Asterisk PBX server. The Asterisk Peer connects fine, but when starting Jigasi, I see the following errors:

`2018-03-22 09:40:59.722 SEVERE: [12] impl.sysactivity.SystemActivityNotificationsServiceImpl.getCurrentRunningManager().647 Error creating manager
java.lang.UnsatisfiedLinkError: no unix-java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at cx.ath.matthew.unix.UnixSocket.<clinit>(UnixSocket.java:40)
	at org.freedesktop.dbus.Transport.connect(Unknown Source)
	at org.freedesktop.dbus.Transport.<init>(Unknown Source)
	at org.freedesktop.dbus.DBusConnection.<init>(Unknown Source)
	at org.freedesktop.dbus.DBusConnection.getConnection(Unknown Source)
	at net.java.sip.communicator.impl.sysactivity.NetworkManagerListenerImpl.<init>(NetworkManagerListenerImpl.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.java.sip.communicator.impl.sysactivity.SystemActivityNotificationsServiceImpl.getCurrentRunningManager(SystemActivityNotificationsServiceImpl.java:643)
	at net.java.sip.communicator.impl.sysactivity.SystemActivityNotificationsServiceImpl.start(SystemActivityNotificationsServiceImpl.java:154)
	at net.java.sip.communicator.impl.sysactivity.SysActivityActivator.start(SysActivityActivator.java:70)
	at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:293)
	at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:460)
	at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:126)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:111)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:17)
	at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:220)
2018-03-22 09:40:59.725 SEVERE: [13] impl.sysactivity.SystemActivityNotificationsServiceImpl.getCurrentRunningManager().647 Error creating manager
java.lang.NoClassDefFoundError: Could not initialize class cx.ath.matthew.unix.UnixSocket
	at org.freedesktop.dbus.Transport.connect(Unknown Source)
	at org.freedesktop.dbus.Transport.<init>(Unknown Source)
	at org.freedesktop.dbus.DBusConnection.<init>(Unknown Source)
	at org.freedesktop.dbus.DBusConnection.getConnection(Unknown Source)
	at net.java.sip.communicator.impl.sysactivity.NetworkManagerListenerImpl.<init>(NetworkManagerListenerImpl.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.java.sip.communicator.impl.sysactivity.SystemActivityNotificationsServiceImpl.getCurrentRunningManager(SystemActivityNotificationsServiceImpl.java:643)
	at net.java.sip.communicator.impl.sysactivity.SystemActivityNotificationsServiceImpl.isSupported(SystemActivityNotificationsServiceImpl.java:597)
	at net.java.sip.communicator.impl.netaddr.NetworkConfigurationWatcher.handleNewSystemActivityNotificationsService(NetworkConfigurationWatcher.java:187)
	at net.java.sip.communicator.impl.netaddr.NetworkConfigurationWatcher.serviceChanged(NetworkConfigurationWatcher.java:243)
	at org.jitsi.impl.osgi.framework.launch.EventDispatcher$Command.run(EventDispatcher.java:117)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:111)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:17)
	at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:220)`

Additionally, I see this error, though it may be less severe:

`2018-03-22 09:41:00.034 SEVERE: [12] org.jitsi.impl.neomedia.device.DeviceConfiguration.log() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer with JMF.
java.lang.IllegalStateException: audioSystem
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:155)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:135)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1046)
	at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:365)
	at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:160)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.initializeService(LibJitsiImpl.java:196)
	at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.getService(LibJitsiImpl.java:131)
	at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:91)
	at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:95)
	at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:172)
	at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:124)
	at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:391)
	at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:293)
	at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:460)
	at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:126)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:111)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:17)
	at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:220)`

When attempting to call a number, it fails saying that it cannot use the socket, which I'm guessing is related to the fact that when it's starting, it can't setup the socket listeners, but that may be extrapolating. Any insight would be appreciated!

**Comment by damencho** [comment]
Seems it is missing the native libs for unix-java, but this is not a problem, it is used by NetworkConfigurationWatcher to check if interface configuration changes so it can reconnect, this is mostly used for jitsi desktop for connecting/disconnecting wifi.
The pulseaudio thing, you can also ignore. 
Can you show what is the actual error about "can't setup the socket listeners"

**Comment by guusdk** [comment]
To resolve the error related to the missing 'unix-java' lib, the `libunix-0.5.1.so` dependency of `org.jitsi:jitsi-sysactivity` must be added to the java.library.path _using the name `libunix-java.so`_ in Linux environments. Note that the file name needs to start with 'lib'.

**Comment by abhijitnathwani** [comment]
Hi @guusdk ,

Can you please elaborate on the solution you found. I added the path to the `SO` in the `java.library.path`, 
However I still see this error when I run the ./jigasi script.

**Comment by guusdk** [comment]
@abhijitnathwani Try adding the path to the directory containing `libunix-java.so`, but excluding the file itself, to `java.library.path`

**Comment by abhijitnathwani** [comment]
I did the same, but no good. I have the file `libunix-0.5.1.so`

**Comment by guusdk** [comment]
Try renaming {{libunix-0.5.1.so}} to {{libunix-java.so}}

**Comment by abhijitnathwani** [comment]
Did that as well, but no good.

**Comment by guusdk** [comment]
That leaves me out of ideas.
